# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a807bbd9ef81020df985e7fa12ec78693c3d392c1349f724fc5fe577c2c7473106542883a16223574bd2c912a018a41ed020a3bec89e473ef77d841bc67e4aea

test:
  secret_key_base: 326ce5e054f37aaceed967c3390c0de03e35575976898f187aa98fc73ff4afa07b7565bddfda80434143843211fd74d72e1282571af2925dcf6b724c36045462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
